### ISSUE TITLE
A (possible) bug in version in 1.4.0 (10400)

### ISSUE THREAD

**Issue by Lukas2112** [jenspfahl/EverydayTasks#30]
Hi, 

I have found a potential bug in the above version. 

## Expected behaviour

After changing a name of a task under the "Tasks" item, they are also automatically updated under "Schedules".

## Actual behaviour: 

After changing a name of a task under the item "Tasks", they are not also updated automatically under "Schedules".

## System information

Mobile Device: Samsung Galaxy A53 5G with "Normal" Samsung Android
Android Version: 13
App-Version: 1.4.0 
Install Source: F-Droid

**Comment by jenspfahl** [comment]
I looked into it and I would tend to say this is expected behavior. Because a schedule has a separate name / title attribute. When you create a new schedule from a task, the schedule's name is prefilled with the name of the task, when you create it from a category it is empty.
You can actually choose a completely different name / title. This could make sense when you have different schedules for the same task. 
Therefore schedule name is not updated when the related task is renamed.
